name: Bundlemon

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Compile Assets
        run: yarn compile:production
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: Run BundleMon
        run: yarn bundlemon
        env:
          BUNDLEMON_PROJECT_ID: 61b93ac52424c30009117f11
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
          NODE_OPTIONS: --openssl-legacy-provider
